version: "3.1"

services:
  compiler-explorer:
    build:
      context: ./
      dockerfile: Dockerfile
    image: madduci/compiler-explorer:latest
    container_name: godbolt-ce
    ports:
      - 10240:10240
    networks:
      - ce_network
    restart: on-failure
    stop_grace_period: 1m30s